# Generated by Django 4.2.11 on 2025-06-28 19:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_text', models.TextField(max_length=400)),
                ('rmbg_picture', models.TextField(blank=True, max_length=400, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('background_image', models.TextField(blank=True, max_length=400, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uploaded Pictures',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_width', models.IntegerField(blank=True, null=True)),
                ('canvas_height', models.IntegerField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('background_path', models.TextField(blank=True, null=True)),
                ('shadow_offset_y', models.FloatField(blank=True, null=True)),
                ('shadow_blur', models.FloatField(blank=True, null=True)),
                ('shadow_color', models.CharField(blank=True, max_length=50, null=True)),
                ('image_x', models.FloatField(blank=True, null=True)),
                ('image_y', models.FloatField(blank=True, null=True)),
                ('image_scale', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('header_height', models.IntegerField(default=0)),
                ('header_color', models.CharField(default='#000000', max_length=50)),
                ('header_opacity', models.FloatField(default=1.0)),
                ('footer_height', models.IntegerField(default=0)),
                ('footer_color', models.CharField(default='#000000', max_length=50)),
                ('footer_opacity', models.FloatField(default=1.0)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_x', models.FloatField(default=100)),
                ('logo_y', models.FloatField(default=100)),
                ('logo_scale', models.FloatField(default=1.0)),
                ('texts', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='rembgApp.uploaded_pictures')),
            ],
        ),
    ]
