# Generated by Django 4.2.11 on 2025-06-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='texts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
