# Generated by Django 4.2.11 on 2025-07-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0002_alter_metadata_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
