# Generated by Django 4.2.11 on 2025-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0003_alter_metadata_logo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_path', models.TextField(blank=True, null=True)),
                ('header_height', models.IntegerField(default=0)),
                ('header_color', models.CharField(default='#000000', max_length=50)),
                ('header_opacity', models.FloatField(default=1.0)),
                ('footer_height', models.IntegerField(default=0)),
                ('footer_color', models.CharField(default='#000000', max_length=50)),
                ('footer_opacity', models.FloatField(default=1.0)),
                ('logo_path', models.TextField(blank=True, null=True)),
                ('logo_x', models.FloatField(default=100)),
                ('logo_y', models.FloatField(default=100)),
                ('logo_scale', models.FloatField(default=1.0)),
                ('texts', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
