# Generated by Django 4.2.11 on 2025-07-16 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0004_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='template_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
