# Generated by Django 4.2.11 on 2025-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_period_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images_used_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_image_limit',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
