# Generated by Django 4.2.11 on 2025-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0007_userprofile_current_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_image_limit',
            field=models.IntegerField(default=0),
        ),
    ]
