# Generated by Django 4.2.11 on 2025-08-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rembgApp", "0008_alter_userprofile_monthly_image_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "User Profile"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
