# Generated by Django 4.2.11 on 2025-08-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rembgApp", "0009_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_monthly_reset_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
