# Generated by Django 4.2.11 on 2025-08-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rembgApp', '0010_userprofile_last_monthly_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('expert', 'Expert'), ('starter-yearly', 'Starter-yearly'), ('pro-yearly', 'Pro-yearly'), ('expert-yearly', 'Expert-yearly')], max_length=20, null=True),
        ),
    ]
