"""
Django settings for rembg_w_python project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

#my edit - This way we are telling Django to use our custom model "User"
#https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'rembgApp.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vq!rgehvyf7(28=8$*f(7^6--jv=m*(z4y8w+6pe(pplkwalnf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rembgApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rembg_w_python.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request', # cashe buster
            ],
        },
    },
]

WSGI_APPLICATION = 'rembg_w_python.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Uploading pictures to media folder
#MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
#MEDIA_URL = '/media/'

# Media file settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'rembg_w_python','media')

CACHE_MIDDLEWARE_SECONDS = 0


#DEBUG = False

# Path where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Custom file paths settings
IMAGE_UPLOAD_ROOT = os.path.join(MEDIA_ROOT, 'images')
BG_TEMPLATES_ROOT = os.path.join(MEDIA_ROOT, 'bg-templates')

# manually change if development or production
ENVIRONMENT = 'development'

if ENVIRONMENT == 'production':
   
   STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET")
   STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
   

   # monthly
   STRIPE_PRICE_ID_STARTER = config("STRIPE_PRICE_ID_STARTER")
   STRIPE_PRICE_ID_PRO = config("STRIPE_PRICE_ID_PRO")
   STRIPE_PRICE_ID_EXPERT = config("STRIPE_PRICE_ID_EXPERT")
   #yearly
   STRIPE_PRICE_ID_STARTER_YEARLY = config("STRIPE_PRICE_ID_STARTER_YEARLY")
   STRIPE_PRICE_ID_PRO_YEARLY = config("STRIPE_PRICE_ID_PRO_YEARLY")
   STRIPE_PRICE_ID_EXPERT_YEARLY = config("STRIPE_PRICE_ID_EXPERT_YEARLY")


else:
    # DEVELOPMENT
    # Run this command to get STRIPE_WEBHOOK_SECRET
    # stripe listen --forward-to 127.0.0.1:8000/webhooks/stripe/ 
    STRIPE_WEBHOOK_SECRET = "whsec_41e9e9a887d089c9a67de75a49fb366623d8ad14dc0d11aebd392bdd1bc4d50c"
    STRIPE_SECRET_KEY = "sk_test_51RqkbeCaEGsYhfdvmNOLR87975Xd4i2tQXnIV2KiVyOou2P2KGg9lr2yCohopdeAHwNGQR7PJJjg4tlgL4JIJUZ200k3lRyEIg"
    # monthly price id
    STRIPE_PRICE_ID_STARTER = "price_1RqoRGCaEGsYhfdvl2BZqPWj"
    STRIPE_PRICE_ID_PRO = "price_1RqoTCCaEGsYhfdvPijlMlir"
    STRIPE_PRICE_ID_EXPERT = "price_1RsWbiCaEGsYhfdv4FlvqP69"
    # yearlt price id
    STRIPE_PRICE_ID_STARTER_YEARLY = "price_1RsWdPCaEGsYhfdvPny2VRwx"
    STRIPE_PRICE_ID_PRO_YEARLY = "price_1RsWeTCaEGsYhfdv8HQXJFAe"
    STRIPE_PRICE_ID_EXPERT_YEARLY = "price_1RsWfICaEGsYhfdv0nc56SQ4"
    


# Celery settings (local Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Optional: Task serializer and time limits
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TIME_LIMIT = 300  # 5 min max per task




#Email setup

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.ionos.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "noreply@autobgpro.com"
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")


# Default sender email
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER