"""
Django settings for rembg_w_python project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

#my edit - This way we are telling Django to use our custom model "User"
#https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'rembgApp.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["18.218.173.51", "localhost", "autobgpro.com", "www.autobgpro.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rembgApp',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rembg_w_python.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request', # cashe buster
            ],
        },
    },
]

WSGI_APPLICATION = 'rembg_w_python.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Uploading pictures to media folder
#MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
#MEDIA_URL = '/media/'

# Media file settings
#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'rembg_w_python','media')

CACHE_MIDDLEWARE_SECONDS = 0



# Path where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# manually change if development or production
ENVIRONMENT = 'production'

if ENVIRONMENT == 'production':
    
   # SECURITY WARNING: keep the secret key used in production secret!
   SECRET_KEY = config('SECRET_KEY')
   
   STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET")
   STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
   

   # monthly
   STRIPE_PRICE_ID_STARTER = config("STRIPE_PRICE_ID_STARTER")
   STRIPE_PRICE_ID_PRO = config("STRIPE_PRICE_ID_PRO")
   STRIPE_PRICE_ID_EXPERT = config("STRIPE_PRICE_ID_EXPERT")
   #yearly
   STRIPE_PRICE_ID_STARTER_YEARLY = config("STRIPE_PRICE_ID_STARTER_YEARLY")
   STRIPE_PRICE_ID_PRO_YEARLY = config("STRIPE_PRICE_ID_PRO_YEARLY")
   STRIPE_PRICE_ID_EXPERT_YEARLY = config("STRIPE_PRICE_ID_EXPERT_YEARLY")
   EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
   
   # AWS S3 Settings
   AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID") #config("AWS_ACCESS_KEY_ID")
   AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
   AWS_STORAGE_BUCKET_NAME = "autobgpro-bkt"
   AWS_S3_REGION_NAME = "us-east-2"  # match your bucket region
   
   # Force private storage
   AWS_DEFAULT_ACL = None  # This is the key setting to fix the error
   AWS_QUERYSTRING_AUTH = False  # requires signed URLs
   AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
   }
   
   # Your AWS S3 bucket name
   AWS_STORAGE_BUCKET_NAME = 'autobgpro-bkt'
   # Set the custom domain for S3. This should be the CNAME record you set up
   # or the default S3 URL for your bucket. 
   AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
   
   
   # AWS S3 storage 
   #DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"
   DEFAULT_FILE_STORAGE =  "rembg_w_python.storage_backends.MediaStorage" #"storages.backends.s3boto3.S3Boto3Storage"
   #DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
   STATICFILES_STORAGE = "storages.backends.s3.S3Storage"
   
   # Media file settings
   MEDIA_URL = 'https://autobgpro-bkt.s3.amazonaws.com/media/'
   MEDIA_ROOT = os.path.join(BASE_DIR, 'rembg_w_python','media')
   
   # Custom file paths settings
   BG_TEMPLATES_ROOT = os.path.join(MEDIA_ROOT, 'bg-templates')
   
   USE_UPLOAD = os.path.join(MEDIA_ROOT, 'user_upload')
   
   # Custom S3 paths
   S3_LOGO_ROOT = 'media/user_upload/user_id_{user_id}/logos/'
   S3_MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
  

else:
    
    # Media file settings
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'rembg_w_python','media')
    # Custom file paths settings
    IMAGE_UPLOAD_ROOT = os.path.join(MEDIA_ROOT, 'images')
    BG_TEMPLATES_ROOT = os.path.join(MEDIA_ROOT, 'bg-templates')
    
    # DEVELOPMENT
    SECRET_KEY = "jjsdfsomethingsecretforlocaldevhfsdjkfhdsjkfhsdkjfhsdkjfh"  # only for development
    
    # Run this command to get STRIPE_WEBHOOK_SECRET
    # stripe listen --forward-to 127.0.0.1:8000/webhooks/stripe/ 
    STRIPE_WEBHOOK_SECRET = "whsec_41e9e9a887d089c9a67de75a49fb366623d8ad14dc0d11aebd392bdd1bc4d50c"
    STRIPE_SECRET_KEY = "sk_test_51RqkbeCaEGsYhfdvmNOLR87975Xd4i2tQXnIV2KiVyOou2P2KGg9lr2yCohopdeAHwNGQR7PJJjg4tlgL4JIJUZ200k3lRyEIg"
    # monthly price id
    STRIPE_PRICE_ID_STARTER = "price_1RqoRGCaEGsYhfdvl2BZqPWj"
    STRIPE_PRICE_ID_PRO = "price_1RqoTCCaEGsYhfdvPijlMlir"
    STRIPE_PRICE_ID_EXPERT = "price_1RsWbiCaEGsYhfdv4FlvqP69"
    # yearlt price id
    STRIPE_PRICE_ID_STARTER_YEARLY = "price_1RsWdPCaEGsYhfdvPny2VRwx"
    STRIPE_PRICE_ID_PRO_YEARLY = "price_1RsWeTCaEGsYhfdv8HQXJFAe"
    STRIPE_PRICE_ID_EXPERT_YEARLY = "price_1RsWfICaEGsYhfdv0nc56SQ4"
    EMAIL_HOST_PASSWORD = ""
    


# Celery settings (local Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Optional: Task serializer and time limits
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TIME_LIMIT = 300  # 5 min max per task


#Email setup

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.ionos.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "noreply@autobgpro.com"
#EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# Default sender email
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER